### ISSUE TITLE
Trouble installing seq2HLA

### ISSUE THREAD

**Issue by ihodes** [hammerlab/biokepi#278]
```
discarding …biopam-kit/conda_dir/bin from PATH
prepending…/biopam-kit/conda_dir/envs/biokepi/bin to PATH
[ERROR] The compilation of seq2HLA failed at "pyinstaller --log-level ERROR```
        seq2HLA.spec".

#=== ERROR while installing seq2HLA.2.2 =======================================#
# opam-version         1.2.2
# os                   linux
# command              pyinstaller --log-level ERROR seq2HLA.spec
# path                …biopam-kit/opam_dir/.opam/0.0.0/build/seq2HLA.2.2
# compiler             0.0.0
# exit-code            255
# env-file             /…seq2HLA.2.2/seq2HLA-30580-548b09.env
# stdout-file         …seq2HLA-30580-548b09.out
# stderr-file         …iopam-kit/opam_dir/.opam/0.0.0/build/seq2HLA.2.2/seq2HLA-30580-548b09.err
### stdout ###
# Missing packaging package!
### stderr ###
# [...]
# 361 ERROR: Hidden import 'packaging.requirements' not found
# 363 ERROR: Hidden import 'packaging.version' not found
# 364 ERROR: Hidden import 'packaging.specifiers' not found
# Traceback (most recent call last):
#   File "<string>", line 2, in <module>
# ImportError: No module named win32com
# Traceback (most recent call last):
#   File "<string>", line 2, in <module>
# ImportError: No module named win32com
# ldd: warning: you do not have execution permission for `/…/biopam-kit/conda_dir/envs/biokepi/lib/python2.7/site-packages/numpy/core/../../../../libgcc_s.so.1'

**Comment by smondet** [comment]
What's your OS?

**Comment by ihodes** [comment]
This is on the cluster, Cent OS 7

**Comment by smondet** [comment]
oh wait 

```
# 361 ERROR: Hidden import 'packaging.requirements' not found
# 363 ERROR: Hidden import 'packaging.version' not found
# 364 ERROR: Hidden import 'packaging.specifiers' not found
```

The `opam` package reports the error `\o/`

You need (at least) to reinstall conda also.

I would wipe-out all tools installations since the recent changes may not be fully aware of the previous state.

**Comment by ihodes** [comment]
I'll give that a try and report back (though I don't think I updated Biokepi anytime recently)

**Comment by smondet** [comment]
Yes but you seem to have caught my PR to `biopam` itself.
