### ISSUE TITLE
OptiType fails to run with the current setup

### ISSUE THREAD

**Issue by armish** [hammerlab/biokepi#418]
@tavinathanson discovered this during his recent trials. Here is the error log of an attempt to run OptiType on a legit data set:

```
Traceback (most recent call last):
  File "<string>", line 114, in <module>
  File "/nfs-pool/biokepi/toolkit/biopam-kit/envs/optitype.1.0.0/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "model.py", line 15, in <module>
  File "/nfs-pool/biokepi/toolkit/biopam-kit/envs/optitype.1.0.0/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/pyomo/environ/__init__.py", line 13, in <module>
  File "/nfs-pool/biokepi/toolkit/biopam-kit/envs/optitype.1.0.0/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/pyomo/core/__init__.py", line 10, in <module>
  File "/nfs-pool/biokepi/toolkit/biopam-kit/envs/optitype.1.0.0/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/pyomo/util/__init__.py", line 10, in <module>
  File "/nfs-pool/biokepi/toolkit/biopam-kit/envs/optitype.1.0.0/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/pyomo/util/_task.py", line 20, in <module>
ImportError: No module named pyutilib.workflow
OptiTypePipeline returned -1
```

Seems that there is something wrong with the way pyutilib and pyomo libraries are interacting, but we weren't able to trace the issue down to a specific cause.

**Comment by tavinathanson** [comment]
Trying with @armish's setup, I get some of these, which I believe are issues with OptiType itself:

```
### Kube-Job 5ae7ce4b-d459-5b3c-a30d-6cd9528d6291
### Freshness: Fresh
### Output:

User
biokepi
Host
5ae7ce4b-d459-5b3c-a30d-6cd9528d6291
Machine
Linux 5ae7ce4b-d459-5b3c-a30d-6cd9528d6291 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 x86_64 x86_64 GNU/Linux
biokepi
biokepi
No export var
/tmp/_MEIq1H09H/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
Killed
Killed

0:00:00.47 Mapping f003a1843a6c739551bcfd981af8afd7_checkpoint-trials_lung_tumor_bams_mafs_SN0110394_bams_mafs_old_samples_IN_MCC_00234_T1_bamIN_MCC_00234_T1-b2fq-PE_R1.fastq to GEN reference...

0:14:11.61 Mapping f003a1843a6c739551bcfd981af8afd7_checkpoint-trials_lung_tumor_bams_mafs_SN0110394_bams_mafs_old_samples_IN_MCC_00234_T1_bamIN_MCC_00234_T1-b2fq-PE_R2.fastq to GEN reference...

0:27:58.74 Generating binary hit matrix.
Traceback (most recent call last):
  File "<string>", line 267, in <module>
  File "hlatyper.py", line 177, in pysam_to_hdf
  File "pysam/calignmentfile.pyx", line 333, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4808)
  File "pysam/calignmentfile.pyx", line 533, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:7027)
IOError: file `tumor_dna_processing_IN_MCC_00234/2017_02_09_10_38_37/2017_02_09_10_38_37_1.bam` not found
OptiTypePipeline returned -1
```

**Comment by tavinathanson** [comment]
(Edit: had some comments here about #419 but just created a separate issue.)

**Comment by tavinathanson** [comment]
This is fixed with @armish's switch to OptiType via bioconda.
