### ISSUE TITLE
Intermittent OptiType issue

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/biokepi#464]
Weird, other BAMs aren't seeing this, and I believe this BAM didn't see this when I ran a few months ago. Maybe will be resolved when I re-run?

```
### Job 0b224e03-df8c-54d8-81ab-446531f11020
### Freshness: Fresh
### Output:

## Biokepi machine: 'umask 000'
## Biokepi machine: 'whoami'
biokepi
## Biokepi machine: 'groups'
biokepi
## Biokepi machine: 'hostname'
0b224e03-df8c-54d8-81ab-446531f11020
## Biokepi machine: 'uname -a'
Linux 0b224e03-df8c-54d8-81ab-446531f11020 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 x86_64 x86_64 GNU/Linux
## Biokepi machine: 'export PATH=/opt/google-cloud-sdk/bin:/opt/google-cloud-sdk/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
## Biokepi machine: 'ls /opt/google-cloud-sdk/bin'
bootstrapping
bq
dev_appserver.py
endpointscfg.py
gcloud
git-credential-gcloud.sh
gsutil
kubectl
Traceback (most recent call last):
  File "/nfs-pool/biokepi/toolkit/biopam-kit/conda_dir/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/nfs-pool/biokepi/toolkit/biopam-kit/conda_dir/lib/python3.5/site-packages/conda/cli/main.py", line 48, in main
    activate.main()
  File "/nfs-pool/biokepi/toolkit/biopam-kit/conda_dir/lib/python3.5/site-packages/conda/cli/activate.py", line 135, in main
    conda.install.symlink_conda(prefix, root_dir, shell)
  File "/nfs-pool/biokepi/toolkit/biopam-kit/conda_dir/lib/python3.5/site-packages/conda/install.py", line 596, in symlink_conda
    symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
  File "/nfs-pool/biokepi/toolkit/biopam-kit/conda_dir/lib/python3.5/site-packages/conda/install.py", line 613, in symlink_conda_hlp
    symlink_fn(root_file, prefix_file)
FileExistsError: [Errno 17] File exists: '/nfs-pool/biokepi/toolkit/biopam-kit/conda_dir/bin/conda' -> '/nfs-pool/biokepi/toolkit/biopam-kit/envs/optitype.1.0.0/bin/conda'
Already in conda env: /nfs-pool/biokepi/toolkit/biopam-kit/envs/optitype.1.0.0
No export var
/tmp/_MEIthkz4o/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.

[...]

0:27:41.70 Generating binary hit matrix.
0:27:41.96 Loading dna_processing_345/2017_05_05_21_03_32/2017_05_05_21_03_32_1.bam started. Number of HLA reads loaded (updated every thousand):
1K...2K...3K...4K...5K...6K...7K...8K...9K...10K...11K...12K...13K...
0:27:53.61 13268 reads loaded. Creating dataframe...
0:27:54.56 Dataframes created. Shape: 13268 x 11179, hits: 7073900 (7073900), sparsity: 1 in 20.97
0:27:55.98 Loading dna_processing_345/2017_05_05_21_03_32/2017_05_05_21_03_32_2.bam started. Number of HLA reads loaded (updated every thousand):
Traceback (most recent call last):
  File "<string>", line 373, in <module>
1K...2K...3K...4K...5K...6K...7K...8K...9K...10K...11K...12K...
0:28:06.19 12574 reads loaded. Creating dataframe...
0:28:07.01 Dataframes created. Shape: 12574 x 11179, hits: 6724492 (6724492), sparsity: 1 in 20.90
0:28:11.64 Alignment pairing completed. 11840 paired, 1934 unpaired, 114 discordant 

0:28:15.34 temporary pruning of identical rows and columns

0:28:16.32 Size of mtx with unique rows and columns: (2768, 1895)
0:28:16.32 determining minimal set of non-overshadowed alleles

0:31:26.93 Keeping only the minimal number of required alleles (278,)

0:31:26.96 Creating compact model...

0:31:29.23 Initializing OptiType model...
WARNING: "site-packages/pyomo/solvers/plugins/solvers/GLPK_old.py", 68, _default_executable
	Could not locate the 'glpsol' executable, which is required for solver 'glpk'
WARNING: Solver does not support multi-threading. Please change the config file accordingly. Falling back to single-threading.
WARNING: "site-packages/pyomo/solvers/plugins/solvers/GLPK_old.py", 68, _default_executable
	Could not locate the 'glpsol' executable, which is required for solver 'glpk'
  File "model.py", line 149, in solve
  File "site-packages/pyomo/opt/base/solvers.py", line 501, in solve
  File "site-packages/pyomo/opt/solver/shellcmd.py", line 121, in available
pyutilib.common._exceptions.ApplicationError: No executable found for solver 'glpk'
OptiTypePipeline returned -1
```
Perhaps related to https://github.com/hammerlab/biokepi/issues/418

**Comment by tavinathanson** [comment]
Maybe an issue with my `conda` setup? Experimenting.

**Comment by rleonid** [comment]
I wonder what [glpk](https://github.com/hammerlab/biokepi/blob/374d929281a75de18b96f7896b9fcc9204f0a276/src/environment_setup/biopam.ml#L71) depends upon.

**Comment by smondet** [comment]
Did the conda-ification of OptiType fix this?

**Comment by tavinathanson** [comment]
Yes, I believe this is no longer applicable now that we're using OptiType via bioconda.

**Comment by eli241** [comment]
Hi!
I have the exact same error while running the test.
I downloaded Optitype via conda and even tried to update it with "conda update optitype"
How did you solve it?
Thanks
Eli
